LibraryLabOne/Controllers/LibController.cs
using LibraryLabOne.Models;
using LibraryLabOne.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace LibraryLabOne.Controllers
{
    public class LibController : Controller
    {
        private readonly AppDbContext _context;

        public LibController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult LoanPage()
        {
            return View();
        }

        public async Task<IActionResult> CustomerList()
        {
            return View(await _context.Customers.ToListAsync());
        }

        public IActionResult SingleCustomer()
        {
            return View();
        }

        public IActionResult CustomerLoans(int id)
        {
            var customer = _context.Customers
                .FirstOrDefault(x => x.Id == id);
            var customerLoans = _context.Loans
                .Where(x => x.CustomerId == id)
                .Include(y => y.Book)
                .Where(b => b.BookId == b.Book.Id);


            var customerLoanedBooks = _context.Loans
                .Include(b => b.Book)
                //.Include(p => p.Customer)
                .Where(c => c.Id == id)
                .ToList();



            var cLoansVModel = new CustomerLoansViewModel()
            {
                Loans = customerLoans,
                Cust = customer
            };

            return View(cLoansVModel);
        }

        public IActionResult CustomerDetails(int id)
        {
            var customer = _context.Customers
                .FirstOrDefault(x => x.Id == id);

            var cDetailsVModel = new CustomerDetailsViewModel()
            {
                Customer = customer
            };
            return View(cDetailsVModel);
        }

        public IActionResult AddCustomer(int id)
        {
            if (id == 0)
            {
                return View(new Customer());
            }
            else
            {
                return View(_context.Customers.Find(id));
            }
        }
        [HttpPost, ActionName("CreateACustomer")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateACustomer([Bind("Id,FirstName,LastName,Email,Books")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                _context.Customers.Add(customer);
                await _context.SaveChangesAsync();
            }
            else
            {
                return RedirectToAction(nameof(CreateACustomer));
            }
            //return View(customer);
            return RedirectToAction(nameof(CustomerList));
        }
        //[ActionName("CreateCustomerForm")]
        public IActionResult CreateACustomer()
        {
            return View();
        }
        public IActionResult EditCustomer(int id)
        {
            var customer = _context.Customers
                .FirstOrDefault(x => x.Id == id);

            var cDetailsVModel = new CustomerDetailsViewModel()
            {
                Customer = customer
            };
            return View(customer);
        }
        public IActionResult UpdateCust(int id)
        {
            if (id == 0)
            {
                return View(new Customer());
            }
            else
            {
                return View(_context.Customers.Find(id));
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateCust([Bind("Id,FirstName,LastName,Email")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                _context.Entry(customer).State = EntityState.Modified;
                _context.SaveChanges();
                RedirectToAction(nameof(CustomerList));
            }
            return RedirectToAction(nameof(CustomerList));
        }
        public async Task<IActionResult> Delete(int id)
        {
            var customer = await _context.Customers.FindAsync(id);
            var anyLoans = _context.Loans.Any(x => x.CustomerId == id);
            if (customer != null)
            {
                if (anyLoans == true)
                {
                    return RedirectToAction(nameof(DeleteError));
                }
                _context.Customers.Remove(customer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(CustomerList));
            }
            return NotFound();
        }
        public IActionResult DeleteError()
        {
            return View();
        }
        public IActionResult ReturnLoanedBook(int id)
        {
            if (id != 0)
            {
                var loanToRemove = _context.Loans.FirstOrDefault(x => x.Id == id);
                if (loanToRemove != null)
                {
                    var bookOfLoan = _context.Books.FirstOrDefault(x => x.Id == loanToRemove.BookId);
                    bookOfLoan.inStock = true;
                    _context.Loans.Remove(loanToRemove);
                    _context.Entry(bookOfLoan).State = EntityState.Modified;
                    _context.SaveChanges();

                }
                //return NotFound("Loan not found");
            }
            //return NotFound("Id was not found");
            return RedirectToAction(nameof(CustomerList));
        }

        public IActionResult SelectListLoan()
        {
            List<SelectListItem> sLICustomers = new List<SelectListItem>() { };
            foreach (var cust in _context.Customers)
            {
                sLICustomers.Add(new SelectListItem { Text = cust.FirstName + cust.LastName, Value = cust.Id.ToString() });
            }
            List<SelectListItem> sLIBooks = new List<SelectListItem>() { };
            foreach (var book in _context.Books)
            {
                if (book.inStock == true)
                {
                    sLIBooks.Add(new SelectListItem { Text = book.Title, Value = book.Id.ToString() });
                }
            }
            //var dictionaryOne = new Dictionary<int, string>();
            //foreach (var cust in _context.Customers)
            //    {
            //    dictionaryOne.Add(cust.Id, cust.FirstName);
            //    }
            //ViewBag.SelectList = new SelectList(dictionaryOne,"Id", "Name");
            //Loan tempLoan = new Loan();
            //SelectList sLCusts = new SelectList(_context.Customers, "CustomerId", "Name", loan.CustomerId);
            //SelectList sLBooks = new SelectList(_context.Books, "BookId", "Title", loan.BookId);

            //ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "FirstName"/*, loan.CustomerId*/);
            //ViewData["BookId"] = new SelectList(_context.Books, "BookId", "Title"/*, loan.BookId*/);
            //var dbCusts = from custies in _context.Customers
            //              select custies;
            //var dbBooks = from bookies in _context.Books
            //              select bookies;
            //var selectListLoanVM = new SelectListLoanViewModel()
            //{
            //    customers = dbCusts,
            //    books = dbBooks
            //};
            //ViewBag.selCusts = new SelectList(_context.Customers, "CustomerId", "Name", tempLoan.CustomerId);
            //ViewBag.selCusts = sLCusts;
            //ViewBag.selBooks = sLBooks;
            //ViewBag.selBooks = new SelectList(_context.Books, "BookId", "Title", tempLoan.BookId);
            ViewBag.MyCustss = sLICustomers;
            ViewBag.MyBookss = sLIBooks;
            //TempLoanViewModel tlvm = new TempLoanViewModel();
            return View();
        }

        [HttpPost]
        public IActionResult StringDetourForFun(TempLoanViewModel tempLoanVM)
        {

            var customerId = Int32.Parse(tempLoanVM.StringCustId);
            var bookId = Int32.Parse(tempLoanVM.StringBookId);
            //Loan tempLoan = new Loan()
            //{
            //    CustomerId = customerId,
            //    BookId = bookId,
            //};

            var StartDateStamp = DateTime.Now;
            var endDate = StartDateStamp.AddDays(15);

            _context.Loans.Add(new Loan() { BookId = bookId, CustomerId = customerId, StartDate = StartDateStamp, EndDate = endDate });
            var bookGotLoaned = _context.Books.Find(bookId);
            bookGotLoaned.inStock = false;
            _context.Books.Update(bookGotLoaned);
            _context.SaveChanges();
            return RedirectToAction(nameof(CustomerList));

            //return RedirectToAction("Index", "Home");
            //return RedirectToAction(AddCustomerAndBookToLoan(tempLoan));
        }
        //public IActionResult CreateLoanView()
        //{
        //    var allBooks = _context.Books.ToList();
        //    var allCust = _context.Customers.ToList();

        //    var createLoanV = new CreateLoanViewModel()
        //    {
        //        books = allBooks,
        //        customers = allCust
        //    };
        //    return View(createLoanV);
        //}
        //public IActionResult SelectedCustomerForLoan(int id)
        //{
        //    var newLoan = new Loan() { };

        //}
        //public async Task<IActionResult> LoanBookPage(int id)
        //{
        //    var newLoan = new Loan() { };
        //    if (newLoan.CustomerId == 0 && newLoan.BookId == 0)
        //    {
        //        newLoan.CustomerId = id;
        //        return View(await _context.Books.ToListAsync());
        //    }
        //    else if(newLoan.CustomerId != 0 && newLoan.BookId == 0)
        //    {
        //        newLoan.BookId = id;
        //        return RedirectToAction(nameof(AddCustomerAndBookToLoan));
        //    }
        //    return RedirectToAction(nameof(CustomerList));
        //}
        [HttpPost]
        [ValidateAntiForgeryToken]

LibraryLabOne/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibraryLabOne</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibraryLabOne.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LibraryLabOne</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" style="padding-right: 3rem; padding-left: 3rem;" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa-solid fa-house-user"></i> Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" style="padding-right: 3rem;" asp-area="" asp-controller="Lib" asp-action="CustomerList"><i class="fa-solid fa-list"></i> All Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" style="padding-right: 3rem;" asp-area="" asp-controller="Lib" asp-action="SelectListLoan"><i class="fa-solid fa-book"></i> Loan</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - LibraryLabOne - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>